### ISSUE TITLE
Build steps

### ISSUE THREAD

**Issue by jackblades** [FrankBro/ordo#11]
Hi, could you please add steps to build the compiler and run the repl? I'm on Mac but i think any set of steps will give some idea.

**Comment by FrankBro** [comment]
Hey man. Sorry I missed the notification. I will try to update the readme to include this but in the meantime, what you want to do is:

1- Install dotnet sdk via `brew cask install dotnet-sdk`
2- Git clone the repo somewhere.
3- From the main folder. To start the repl, run `dotnet run`. This should fetch dependencies and start the repl. 

There's a whole bunch of tests to look at if you wanna figure stuff. The readme has a lot too. I'm be more than happy to answer any questions about the compile, type system, inference .. anything. 

I was pretty actively working on it until advent of code happened, will probably continue at some point after december.
